//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Productos", Namespace="http://schemas.datacontract.org/2004/07/Wcf.Controller")]
    [System.SerializableAttribute()]
    public partial class Productos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaFacturaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaFacturaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaFactura {
            get {
                return this.FechaFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaFacturaField, value) != true)) {
                    this.FechaFacturaField = value;
                    this.RaisePropertyChanged("FechaFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaFacturaFin {
            get {
                return this.FechaFacturaFinField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaFacturaFinField, value) != true)) {
                    this.FechaFacturaFinField = value;
                    this.RaisePropertyChanged("FechaFacturaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaFacturaInicio {
            get {
                return this.FechaFacturaInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaFacturaInicioField, value) != true)) {
                    this.FechaFacturaInicioField = value;
                    this.RaisePropertyChanged("FechaFacturaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFactura {
            get {
                return this.IdFacturaField;
            }
            set {
                if ((this.IdFacturaField.Equals(value) != true)) {
                    this.IdFacturaField = value;
                    this.RaisePropertyChanged("IdFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProducto {
            get {
                return this.NombreProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreProductoField, value) != true)) {
                    this.NombreProductoField = value;
                    this.RaisePropertyChanged("NombreProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioTotal {
            get {
                return this.PrecioTotalField;
            }
            set {
                if ((this.PrecioTotalField.Equals(value) != true)) {
                    this.PrecioTotalField = value;
                    this.RaisePropertyChanged("PrecioTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductos", ReplyAction="http://tempuri.org/IService1/GetProductosResponse")]
        WebApp.ServiceReference1.Productos[] GetProductos(WebApp.ServiceReference1.Productos prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductos", ReplyAction="http://tempuri.org/IService1/GetProductosResponse")]
        System.Threading.Tasks.Task<WebApp.ServiceReference1.Productos[]> GetProductosAsync(WebApp.ServiceReference1.Productos prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarProductos", ReplyAction="http://tempuri.org/IService1/MostrarProductosResponse")]
        WebApp.ServiceReference1.Productos[] MostrarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MostrarProductos", ReplyAction="http://tempuri.org/IService1/MostrarProductosResponse")]
        System.Threading.Tasks.Task<WebApp.ServiceReference1.Productos[]> MostrarProductosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApp.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApp.ServiceReference1.IService1>, WebApp.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApp.ServiceReference1.Productos[] GetProductos(WebApp.ServiceReference1.Productos prod) {
            return base.Channel.GetProductos(prod);
        }
        
        public System.Threading.Tasks.Task<WebApp.ServiceReference1.Productos[]> GetProductosAsync(WebApp.ServiceReference1.Productos prod) {
            return base.Channel.GetProductosAsync(prod);
        }
        
        public WebApp.ServiceReference1.Productos[] MostrarProductos() {
            return base.Channel.MostrarProductos();
        }
        
        public System.Threading.Tasks.Task<WebApp.ServiceReference1.Productos[]> MostrarProductosAsync() {
            return base.Channel.MostrarProductosAsync();
        }
    }
}
