USE [master]
GO

/****** Object:  Database [Lab2DB]    Script Date: 8/19/2015 3:00:42 PM ******/
DROP DATABASE [Lab2DB]
GO

/****** Object:  Database [Lab2DB]    Script Date: 8/19/2015 3:00:42 PM ******/
CREATE DATABASE [Lab2DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Lab2DB', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Lab2DB.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Lab2DB_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Lab2DB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Lab2DB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lab2DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Lab2DB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Lab2DB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Lab2DB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Lab2DB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Lab2DB] SET ARITHABORT OFF 
GO

ALTER DATABASE [Lab2DB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Lab2DB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Lab2DB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Lab2DB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Lab2DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Lab2DB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Lab2DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Lab2DB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Lab2DB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Lab2DB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Lab2DB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Lab2DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Lab2DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Lab2DB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Lab2DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Lab2DB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Lab2DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Lab2DB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Lab2DB] SET RECOVERY FULL 
GO

ALTER DATABASE [Lab2DB] SET  MULTI_USER 
GO

ALTER DATABASE [Lab2DB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Lab2DB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Lab2DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Lab2DB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Lab2DB] SET  READ_WRITE 
GO


